### ISSUE TITLE
问下 前端的 图片刷出蒙版区域 调的是哪些框架

### ISSUE THREAD

**Issue by cutemurphy2022** [ali-vilab/MimicBrush#12]
问下 前端的 图片刷出蒙版区域 调的是哪些框架

**Comment by XavierCHEN34** [comment]
用的 gradio，里面自带各种组件

**Comment by cutemurphy2022** [comment]
好的👌

---- 回复的原邮件 ----
| 发件人 | Xi ***@***.***> |
| 发送日期 | 2024年07月01日 22:43 |
| 收件人 | ali-vilab/MimicBrush ***@***.***> |
| 抄送人 | cutemurphy2022 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ali-vilab/MimicBrush] 问下 前端的 图片刷出蒙版区域 调的是哪些框架 (Issue #12) |

用的 gradio，里面自带各种组件
