### ISSUE TITLE
SAM 数据集是如何帮助提高训练的？

### ISSUE THREAD

**Issue by civilman628** [ali-vilab/MimicBrush#13]
SAM 可以提供source  image 的物体的mask, 但是ref image 怎么找？既要保证多样性，又要保证两个图片相关。

原文里有一句：We construct pseudo frames by applying strong data augmentations on the static images from SAM and leverage the object segmentation results for masking the source image. 这句话非常模糊。

**Comment by XavierCHEN34** [comment]
单张图像做Augmentation用来模拟图像对

**Comment by civilman628** [comment]
我觉得不明确，你把一张图片里的一个对象（或对象的局部）用SAM做mask，然后用什么方式做增强可以得到真正有意义的ref图片？因为并不是随机配对都是有意义的组合。比如原文的第一张图片，如果把source image的鞋底用SAM生成一个mask, 你怎么通过图片增强得到一张有意义的ref image？调整颜色？那ref image 的完整性或风格就破坏了。或者把鞋底替换成另外一个对象？那它就不是鞋了。

其他文章例如 
Paint by Example: Exemplar-based Image Editing with Diffusion Models 和 
InstructPix2Pix: Learning to Follow Image Editing Instructions， 等文章都介绍了非常详细的数据生成方法，因为简单的策略会导致非常明显的瑕疵，例如copy/paste effect, 这些文章做了专门的工作去对抗或者避免这些瑕疵，这是非常重要的部分。也就是说用合成的数据去训练是非常谨慎的，因为很容易变成data bias，而你的文章对此没有详细的描述。

**Comment by XavierCHEN34** [comment]
Sec 3.3
Data augmentation. To increase the variation between the source image and the reference image, we exert strong data augmentations. Besides applying the aggressive color jitter, rotation, resizing, and flipping, we also implement random projection transformation to simulate the stronger deformation.

Sec 4.1
We construct pseudo frames by applying strong data augmentations on the static images from SAM and leverage the object segmentation results for masking the source image. During training, the sampling portions of the video and SAM data are 70% versus 30% as default.

如果只用图像的话,  简单的aug策略(甚至复杂的aug策略)都是不行得。所以大部分还是用视频，但是引入图像在扩充类目多样性上非常有效。 图像和视频一起训练这个原则和之前我们的AnyDoor是一样的

**Comment by civilman628** [comment]
你的Sec 3.3 和 Sec 4.1说了等于没说，这根本就是模板和套话。你根本就没解释如何用SAM生成有效的数据对，以及为什么这样做是有效的。因为在我看来简单的mask一下对象，然后随机做一下color jitter, rotation, resizing, and flipping根本就不可能生成有效的数据对。如果这种简单粗暴的策略都行，那么其他文章做的工作都白做了。因此，我觉得你的论文不可信。

**Comment by XavierCHEN34** [comment]
我已经反复说了  1.大部分数据是视频，这个是基础  2.如果只用图像的话, 简单的aug策略(甚至复杂的aug策略)都是不行得 3.但是在视频的基础上加入大量类目的图像对于提升泛化性非常有效。 

加图像数据又不是我的创新点，反而还让这篇文章显得复杂，要不是它非常有效我根本不想在论文提它。如果是讲故事的话，说“纯用视频数据训练” 这个故事不是更吸引人么？

建议多动手实验一下。AnyDoor放了训练代码，也是视频数据+ Aug后的图像数据，你可以试试单独用视频数据训练 和 视频+图像数据训练有没有区别。此外，你说的Paint-by-example除了数据扩充有做啥其他的么？

**Comment by XavierCHEN34** [comment]
你说"这些文章做了专门的工作去对抗或者避免这些瑕疵"的 paint-by-example是这样写的

Reference image augmentation. The first mismatch is that the reference image xr is derived from the source image xs during training, which is barely the case for the testing scenario. To reduce the gap, we adopt several data augmentation techniques (including flip, rotation, blur and elastic transform) on the reference image to break down the connection with the source image.

他写的还没我详细，到我这就是套话，到他那就是“非常详细”？

**Comment by XavierCHEN34** [comment]
> 你的Sec 3.3 和 Sec 4.1说了等于没说，这根本就是模板和套话。你根本就没解释如何用SAM生成有效的数据对，以及为什么这样做是有效的。因为在我看来简单的mask一下对象，然后随机做一下color jitter, rotation, resizing, and flipping根本就不可能生成有效的数据对。如果这种简单粗暴的策略都行，那么其他文章做的工作都白做了。因此，我觉得你的论文不可信。

咱要讨论就把这个讨论好，我是不认你这随便喷的

**Comment by civilman628** [comment]
问题是通过提取不同的视频帧作为训练数据，以及用SAM去mask object，根本解决不了你想解决的问题。AnyDoor是**对象**级别的编辑，用视频帧当然可以。但是你做的是比object更底层的对象局部inpainting，比如改鞋底。这在你的训练数据里完全体现不出来，无论是视频帧还是SAM都没有比object更局部的数据。而且你也没回答我的原始问题，你把鞋底mask之后你的ref image怎么生成？单纯color jitter, rotation, resizing, and flipping就可以生成有效的局部编辑数据对？？？我不跟你debate了，你自己投稿看看reviewer怎么评价。

**Comment by XavierCHEN34** [comment]
你看看论文啊。视频帧我是随便 mask一个frame的局部grid，然后用另外一个frame去补全，这个随机的mask就会包含很多局部啊。

举例有一个鞋的多角度视频，我把frame 1随机mask一部分， 用frame2去补全，随机mask的部分就有可能落在“鞋底，logo”等等各种局部的区域啊。这个就是和测试完全对齐的呀。 

而且 SAM的mask有局部区域的。

牛👍🏻

**Comment by civilman628** [comment]
直接上结果，你说的你策略有效，来看看你的模型的结果吧

我的原图：
![thumbnail_IMG_5987](https://github.com/user-attachments/assets/7087c544-4cdc-4a79-a237-6b1772f11b22)

参考图片：

![61wHoR7q37L _AC_SX679_](https://github.com/user-attachments/assets/8e85fed2-c5d8-4220-98c7-7d0adbfdef19)

我MASK了一个耳机

![Mask](https://github.com/user-attachments/assets/307951b6-adc6-4f6c-834a-9b90d3d4c889)


你的模型的生成结果：

![image](https://github.com/user-attachments/assets/eb497316-8f35-4bde-9036-414649958766)


你的算法哪里有效了~~~~这个结果完全证实了我的猜测，原图和参考图像根本就匹配不上，因为你的模型和数据生成策略完全是错的。

**Comment by XavierCHEN34** [comment]
牛  没话说了😂  
看来你就真的就完全没看懂。这个文章是利用语义对应关系做图像编辑，你把一个耳机mask掉，从哪知道这个语义对应的是啥。
祝您开心
