### ISSUE TITLE
question about comparison methods

### ISSUE THREAD

**Issue by hrz2000** [ali-vilab/MimicBrush#16]
![image](https://github.com/user-attachments/assets/a6426afb-ed50-48ab-850b-50aadcd3711a)
Both anydoor and pbe need mask, and w/o mask refers to how to do it? Is it to treat the entire image as an inpainting area?

**Comment by XavierCHEN34** [comment]
No, all the methods(including ours) require the masks for the source image to indicate the to-edit region. We are talking about the mask/box for the "reference image". AnyDoor needs to segment out the region that users want to insert from the reference image to the source image. W/o mask means taking the full reference image

**Comment by hrz2000** [comment]
tks for your quickly reply~

**Comment by hrz2000** [comment]
By the way, there is a related question, why PBE is box, Anydoor is mask, when considering the reference image, the question to consider is actually whether the reference image is only the foreground or the full image, Why is PBE a BOX?

**Comment by XavierCHEN34** [comment]
PBE's paper uses a box to crop out the reference object. The model is trained using the box, thus we keep the original setting.  
Besides, PBE leverages a single CLIP image token to represent the reference object ( AnyDoor uses 257 tokens). In this way, the information for the reference object is largely bottlenecked, and some of the background pixels in the box region could be neglected

**Comment by hrz2000** [comment]
Thanks！
