### ISSUE TITLE
Good job! Is there difference between resampler and linear peojection?

### ISSUE THREAD

**Issue by cyysc1998** [ali-vilab/MimicBrush#6]
Thanks for sharing the excellent work! I notice that you use Linear projection instead of resampler in ip-adapter.  (https://github.com/ali-vilab/MimicBrush/blob/main/mimicbrush/mimicbrush_referencenet.py#L45). In my opinion, both of them provide the feature of clip patch embedding. Cloud you tell me the motivation or their affects in the experiment? Thank you!

**Comment by XavierCHEN34** [comment]
The resampler in ip-adapter is more complicated for the implementation, and it compresses the tokens into a smaller number.  We found it not necessary for MimicBrush as we have a strong Ref UNet, so we used a simple linear layer instead.  Besides, as we remove the "token compression", our linear resampler could keep more information for the details.
