### ISSUE TITLE
It’s so difficult to control the outline with the brush

### ISSUE THREAD

**Issue by Nuclear6** [ali-vilab/MimicBrush#8]
It's difficult to draw precise outlines with this set of brushes, and this area looks a bit affected.

**Comment by Nuclear6** [comment]
<img width="1543" alt="image" src="https://github.com/ali-vilab/MimicBrush/assets/49468241/9de473fc-9b82-40d0-a048-2edee5fd0df8">
<img width="758" alt="image" src="https://github.com/ali-vilab/MimicBrush/assets/49468241/8168f7e0-ca7a-493a-bf74-8f7f6b91218f">

**Comment by XavierCHEN34** [comment]
Would it help if you set keep_original_shape as True?
