### ISSUE TITLE
Inquiry About Some Details

### ISSUE THREAD

**Issue by Jonyond-lin** [ali-vilab/MimicBrush#9]
Thank you for your nice work! It's highly inspiring. I have some questions regarding certain details and would greatly appreciate your guidance.

In the "Model Structure" section, it is mentioned that "**The imitative U-Net is initialized with a stable diffusion-1.5 [33] inpainting model. It takes a tensor with 13 channels as the input.**" My understanding is that this involves using the pre-trained model provided by diffusers and concatenating the results of multiple VAE (frozen) modalities. Is this correct? How exactly is the U-Net with 13 channels input initialized in this context?

**Comment by XavierCHEN34** [comment]
Yes, the standard SD inpainting owns 9 channels, we changed it to 13 channels( with an additional 4 depth channels). In this way, the first conv_in layer is randomly initialized, and other weights are initialized with the standard SD inpainting.

**Comment by Jonyond-lin** [comment]
> Yes, the standard SD inpainting owns 9 channels, we changed it to 13 channels( with an additional 4 depth channels). In this way, the first conv_in layer is randomly initialized, and other weights are initialized with the standard SD inpainting.

Thank you for your detailed response. By the way, will the training code for the model be released like the Anydoor?

**Comment by XavierCHEN34** [comment]
> > Yes, the standard SD inpainting owns 9 channels, we changed it to 13 channels( with an additional 4 depth channels). In this way, the first conv_in layer is randomly initialized, and other weights are initialized with the standard SD inpainting.
> 
> Thank you for your detailed response. By the way, will the training code for the model be released like the Anydoor?

Currently no.
